### ISSUE TITLE
`FileExistsError` raised when running test suite in parallel

### ISSUE THREAD

**Issue by kurtmckee** [pytest-dev/pyfakefs#1009]
**Describe the bug**

I ran the test suite across multiple Python interpreter versions in parallel and found what appears to be an isolation issue. In particular, several tox environments reported the following errors:

```
======================================================================
ERROR: test_add_existing_real_directory_symlink (pyfakefs.tests.fake_filesystem_test.RealFileSystemAccessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2298, in test_add_existing_real_directory_symlink
    with self.create_symlinks(symlinks):
  File "/home/kurt/.pyenv/versions/3.10.14/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2257, in create_symlinks
    os.symlink(link[0], link[1])
FileExistsError: [Errno 17] File exists: '..' -> '/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fixtures/symlink_dir_relative'

======================================================================
ERROR: test_add_existing_real_directory_symlink_lazy_read (pyfakefs.tests.fake_filesystem_test.RealFileSystemAccessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2435, in test_add_existing_real_directory_symlink_lazy_read
    with self.create_symlinks(symlinks):
  File "/home/kurt/.pyenv/versions/3.10.14/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2257, in create_symlinks
    os.symlink(link[0], link[1])
FileExistsError: [Errno 17] File exists: '..' -> '/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fixtures/symlink_dir_relative'

======================================================================
ERROR: test_add_existing_real_directory_symlink_target_path (pyfakefs.tests.fake_filesystem_test.RealFileSystemAccessTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2410, in test_add_existing_real_directory_symlink_target_path
    with self.create_symlinks(symlinks):
  File "/home/kurt/.pyenv/versions/3.10.14/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fake_filesystem_test.py", line 2257, in create_symlinks
    os.symlink(link[0], link[1])
FileExistsError: [Errno 17] File exists: '..' -> '/home/kurt/dev/pr-pyfakefs/pyfakefs/tests/fixtures/symlink_dir_relative'
```

**How To Reproduce**

With tox 4.15.0 installed, I ran this command and saw the errors above for several Python interpreters:

```bash
tox run-parallel  # `tox p` for short
```

Running the command again resulted in a different list of failed Python interpreters. In contrast, running the test suite in serial allowed all tests to succeed across all interpreters:

```bash
tox run  # `tox` for short
```

**Your environment**

_Note: My virtual environment doesn't include pytest, but I have tox 4.15.0 installed via pipx for running the test suite._

```
Linux-6.5.0-28-generic-x86_64-with-glibc2.35
Python 3.12.3 (main, Apr 10 2024, 14:08:50) [GCC 11.4.0]
pyfakefs 5.5.dev0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pytest'
```

**Comment by mrbean-bremen** [comment]
No, thank you - this covers it nicely!
