### ISSUE TITLE
shutil.copystat raises AttributeError when used on symlinks

### ISSUE THREAD

**Issue by henniss** [pytest-dev/pyfakefs#799]
**Describe the bug**
shutil.copystat(s,d,follow_symlink=False) raises AttributeError while patched with fake_filesystem_unittest and when both s, d are symlinks.  This looks to be related to github.com/pytest-dev/pyfakefs/issues/533

```
Traceback (most recent call last):
  File "/usr/local/google/home/henniss/github/pyfakefs/pyfakefs/tests/fake_filesystem_shutil_test.py", line 241, in test_copystat_symlinks
    shutil.copystat(sym1, sym2, follow_symlinks=False)
  File "/usr/lib/python3.10/shutil.py", line 373, in copystat
    mode = stat.S_IMODE(st.st_mode)
AttributeError: 'NoneType' object has no attribute 'st_mode'
```

**How To Reproduce**
I'm including a PR which adds a (failing) test: 

**Your environment**

```
python -c "import sys; print('Python', sys.version)"
python -c "from pyfakefs.fake_filesystem import __version__; print('pyfakefs', __version__)"
python -c "import pytest; print('pytest', pytest.__version__)"
Linux-5.19.11-1rodete1-amd64-x86_64-with-glibc2.36
Python 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name '__version__' from 'pyfakefs.fake_filesystem' (/usr/local/google/home/henniss/github/pyfakefs/pyfakefs/fake_filesystem.py)
pytest 7.2.2
```

(n.b. this fails at head, Import error above notwithstanding).

**Comment by mrbean-bremen** [comment]
Thanks, I will have a look!

**Comment by mrbean-bremen** [comment]
Shall be fixed in main now, please check!

**Comment by henniss** [comment]
LGTM, thanks for the quick fix!

**Comment by mrbean-bremen** [comment]
It is now in the latest released version.
