### ISSUE TITLE
Python 3.12 beta1: 'PosixPath' object has no attribute '_drv'

### ISSUE THREAD

**Issue by buhtz** [pytest-dev/pyfakefs#831]
Related to #830

`--version` on TravisCI returns `Python 3.12.0a2+`. Not sure if this is different from "3.12 beta1".

Here is another error in a `pyfakefs` using unittest.

```
======================================================================
ERROR: test_uuid_via_filesystem (test.test_tools.TestTools.test_uuid_via_filesystem)
Extract UUID from /dev filesystem.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 464, in __str__
    return self._str
           ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.12-dev/lib/python3.12/site-packages/pyfakefs/fake_filesystem_unittest.py", line 142, in wrapped
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/travis/build/bit-team/backintime/common/test/test_tools.py", line 482, in test_uuid_via_filesystem
    fake_fs.create_dir(path_dev)
  File "/home/travis/virtualenv/python3.12-dev/lib/python3.12/site-packages/pyfakefs/fake_filesystem.py", line 2037, in create_dir
    dir_path = self.make_string_path(directory_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/travis/virtualenv/python3.12-dev/lib/python3.12/site-packages/pyfakefs/fake_filesystem.py", line 2015, in make_string_path
    path_str = make_string_path(path)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/travis/virtualenv/python3.12-dev/lib/python3.12/site-packages/pyfakefs/helpers.py", line 123, in make_string_path
    return cast(AnyStr, os.fspath(dir_name))
                        ^^^^^^^^^^^^^^^^^^^
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 471, in __fspath__
    return str(self)
           ^^^^^^^^^
  File "/opt/python/3.12-dev/lib/python3.12/pathlib.py", line 466, in __str__
    self._str = self._format_parsed_parts(self._drv, self._root,
                                          ^^^^^^^^^
AttributeError: 'PosixPath' object has no attribute '_drv'
```

The related code
https://github.com/buhtz/backintime/blob/a80b655229207f90cd2552bec4bc869e597aa024/common/test/test_tools.py#L473-L513

**Comment by hugovk** [comment]
> `Python 3.12.0a2+`. Not sure if this is different from "3.12 beta1".

`3.12.0a2` means "Python 3.12.0 alpha 2" (released 2022-11-14). The `+` usually indicates it some commits later than the tag, but probably before alpha 3.

* https://peps.python.org/pep-0693/

So Travis is quite far behind. GitHub Actions is more up-to-date, and this project's CI is already testing 3.12 which is good to see 👍 

Here's a build from last week, showing it using 3.12.0-alpha.7 (released 2023-04-04):

* https://github.com/pytest-dev/pyfakefs/actions/runs/5013473333/jobs/8986598070#step:3:17

**Comment by mrbean-bremen** [comment]
GH Actions are up to date, they already use 3.12 beta1 as of today.
Fixing this will take a bit more time, I think - there are hundreds of tests failing, mainly because faking `open` doesn't work anymore. There are also some more changes to `pathlib`, though I did expect this, given the history.

I will see if I can get this done over the weekend - I hope that the problem with `open` is relatively easy to solve.

**Comment by buhtz** [comment]
I can confirm you are right.

After TravisCI no supports `Python 3.12.0b1+` there is no error anymore.
